config/routes.rb
SampleApp::Application.routes.draw do
  resources :entities

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :entities do
    get "load_image", :on => :member
  end
  resources :sessions,   only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/game', to: 'static_pages#game', via: 'get'
  match '/entities/createnew' => 'entities#create_new' , via: 'post', :as => :entities_create_new
  match '/entities/allonlyposition' => 'entities#all_only_position' , via: 'post', :as => :entities_all_only_position
  match '/entitiesgame' => 'entities#game' , via: 'get', :as => :entities_game
  match '/entities/:id/addtags' => 'entities#addtags' , via: 'post', :as => :entities_addtags
  match '/users/:id/updatescore' => 'users#updatescore' , via: 'post', :as => :users_updatescore

  

end

app/models/entity.rb
class Entity < ActiveRecord::Base
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: [:show, :edit, :update, :destroy]

  # GET /entities
  # GET /entities.json
  def index
    @entities = Entity.all
  end

  def all
    @entities = Entity.all
  end

  def all_only_position
    @entities = Entity.all
    @body = [@entities.length]
    count = 0
    @entities.each do |item|
      @body[count] = {
          "id" => item.id,
          "latitude" => item.latitude,
          "longitude" => item.longitude
      }
      count += 1
    end

    puts @body.to_json

    render :text => @body.to_json
=begin

    respond_to do |format|
      if params[:callback]
        format.js { render :json => {:running => @body}, :callback => params[:callback] }
      else
        format.json { render json: {:running => @body} }
      end
    end
=end
  end

  def game
    @entities = Entity.order("RANDOM()").limit(10)
  end
  
 def addtags
   @entity = Entity.find(params[:id])
 if (@entity.tags == nil || @entity.tags == "")
   @entity.tags = params[:tags]  
 else
   @entity.tags =  @entity.tags + " " + params[:tags]
   a = @entity.tags
   b = a.split(' ').uniq.join(' ')
   @entity.tags = b
 end
 @entity.save
 end
  
  # GET /entities/1
  # GET /entities/1.json
  def show
  end

  # GET /entities/new
  def new
    @entity = Entity.new
  end

  # GET /entities/1/edit
  def edit
  end

  # POST /entities
  # POST /entities.json
  def create

    @entity = Entity.new()

    if params[:entity][:image]
      @entity.image = params[:entity][:image].read
      @entity.filename = params[:entity][:image].original_filename
      @entity.mine_type = params[:entity][:image].content_type
    end

    @entity.latitude = params[:entity][:latitude]
    @entity.longitude = params[:entity][:longitude]

    if @entity.save
      redirect_to(@entity, :notice => 'Photo was successfully created.')
    else
      render :action => "new"
    end

    respond_to do |format|
      if @entity.save
        format.html { redirect_to @entity, notice: 'Entity was successfully created.' }
        format.json { render action: 'show', status: :created, location: @entity }
      else
        format.html { render action: 'new' }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_new

    @entity = Entity.new()

    if params[:file]
      @entity.image = params[:file].read
      @entity.filename = params[:file].original_filename
      @entity.mine_type = params[:file].content_type
    end

puts "longitude"

    @entity.latitude = params[:latitude]
    @entity.longitude = params[:longitude]

    @entity.save
  end

  def load_image
    @entity = Entity.find(params[:id])
    puts @entity.mine_type + " " + @entity.filename
    send_data(@entity.image, :type => @entity.mine_type, :filename => "#{ @entity.filename }.jpg", :disposition => "inline")
  end

  # PATCH/PUT /entities/1
  # PATCH/PUT /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to @entity, notice: 'Entity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1
  # DELETE /entities/1.json
  def destroy
    @entity.destroy
    respond_to do |format|
      format.html { redirect_to entities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entity
      @entity = Entity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entity_params
      params.require(:entity).permit(:image, :latitude, :longitude, :mine_type, :filename)
    end
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/entities/_form.html.erb
<%= form_for(@entity) do |f| %>
  <% if @entity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
      <% @entity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :mine_type %><br>
    <%= f.text_field :mine_type %>
  </div>
  <div class="field">
    <%= f.label :filename %><br>
    <%= f.text_field :filename %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entities/edit.html.erb
<h1>Editing entity</h1>

<%= render 'form' %>

<%= link_to 'Show', @entity %> |
<%= link_to 'Back', entities_path %>

app/views/entities/game.html.erb
<h1>Game</h1>

<%= javascript_include_tag "bpopup.min.js", "data-turbolinks-track" => true %>

<p style="text-align: justify"><b>Instruction:</b> This game is played like the famous Memory or Concentration game. Uncover and memorize one pictures. Then uncover and memorize the second. If they are the same, both cards remain open, if that's not the case, both cards are closed again. The goal is to uncover all the cards with as little looks on the cards as possible. This game differts from other similar memory games through an useful search and tag function. Every pictures can be tagged before it gets closed again. A search function highlights the different cards tagged with the searched tag. This does not only help the user complete the game faster but also gives important meta data for the pictures.</p> 

<script type="text/javascript">
    var boxopened1 = "";
    var boxopened2 = "";
    var imgopened = "";
    var currentopened = "";
    var count = 0;
    var found =  0;
    var state = false;
    var score = 0;

    function tag(){
        $("#"+ boxopened1 +" img").addClass(document.forms[1].elements[0].value);
        var id = imgopened.substring(51, (imgopened.length - 11));
        alert(id);
		$.ajax({
	                            url: "entities/" + id + "/addtags",
	                            contentType: "application/json",
	                            type: "POST",
	                            data: JSON.stringify({ id: id, tags: document.forms[1].elements[0].value }),
	                            success: function (result) {
	                            },
	                            error: function (result) {                       
	                         }
	                        });
    }


    function search(){
        $("img." + document.forms[0].elements[0].value).parent().attr("style", "border: 1px solid #FF0000;");

        setTimeout(function() {
            $("img." + document.forms[0].elements[0].value).parent().attr("style", "none");
        }, 2000);
    }

    function randomFromTo(from, to){
        return Math.floor(Math.random() * (to - from + 1) + from);
    }

    function shuffle() {
        var children = $("#boxcard").children();
        var child = $("#boxcard div:first-child");

        var array_img = new Array();

        for (i=0; i<children.length; i++) {
            array_img[i] = $("#"+child.attr("id")+" img").attr("src");
            child = child.next();
        }

        var child = $("#boxcard div:first-child");

        for (z=0; z<children.length; z++) {
            randIndex = randomFromTo(0, array_img.length - 1);

            // set new image
            $("#"+child.attr("id")+" img").attr("src", array_img[randIndex]);
            array_img.splice(randIndex, 1);

            child = child.next();
        }
    }

    function resetGame() {
        shuffle();
        $("#boxcard div img").hide();
        $("img").removeClass("opacity");
        count = 0;
        $("#msg").remove();
        $("#count").html("" + count);
        boxopened1 = "";
        imgopened = "";
        found = 0;
        return false;
    }


    $(document).ready(function() {
        $("#boxcard div img").hide();
        $("#boxcard div").click(openCard);

        shuffle();

                            $.ajax({
                                url: "users/" + id + "/updatescore", 
                                contentType: "application/json",
                                type: "POST",
                                data: JSON.stringify({ id: id, score: $("span.link").value}),
                                success: function (result) {
                                },
                                error: function (result) {                       
                             }
                            }); 

        function openCard() {
            id = $(this).attr("id");

            if ($("#"+id).attr("class") == "opencard")
                $("#element_to_pop_up").bPopup();
            
            if ($("#"+id+" img").is(":hidden")) {
                $("#boxcard div").unbind("click", openCard);
                $("#"+id+" img").slideDown("fast");
                $("#"+id).addClass("opencard");

                if (imgopened == "") {
                    boxopened1 = id;
                    imgopened = $("#"+id+" img").attr("src");
                        $("#element_to_pop_up").html("<img src=" + imgopened + " height='800' width='533'/> <form action='javascript:tag();' method='post'> <br>  <input type='text' value='" + $("#"+id+" img").attr('class') + "'/> <input type='submit' value='Tag' /> </form>");
                    setTimeout(function() {
                        $("#boxcard div").bind("click", openCard);
                    }, 400);
                } else {
                    boxopened2 = id;
                    currentopened = $("#"+id+" img").attr("src");
                        $("#element_to_pop_up").html("<img src=" + currentopened + " height='800' width='533'/> <form action='javascript:tag();' method='post'> <br>  <input type='text' value='" + $("#"+id+" img").attr('class') + "'/> <input type='submit' value='Tag' /> </form>");
                    if (imgopened != currentopened) {
                        // close again
                        setTimeout(function() {
                            $("#"+id+" img").slideUp("fast");
                            $("#"+boxopened1 +" img").slideUp('fast');
                            $("#"+boxopened1).removeClass("opencard");
                            $("#"+boxopened2).removeClass("opencard");
                            boxopened1 = "";
                            imgopened = "";
                        }, 400);
                    } else {
                        // found
                        // $("#"+id+" img").addClass("opacity");
                        // $("#"+boxopened+" img").addClass("opacity");
                        $("#"+id).addClass("opencard");
                        $("#element_to_pop_up").html("<img src=" + currentopened + " height='800' width='533'/> <form action='javascript:tag();' method='post'> <br>  <input type='text' value='" + $("#"+id+" img").attr('class') + "'/> <input type='submit' value='Tag' /> </form>");
                        found++;
                        boxopened1 = "";
                        imgopened = "";
                    }
                    
                    setTimeout(function() {
                        $("#boxcard div").bind("click", openCard);
                    }, 400);
                }

                count++;
                $("#count").html("" + count);

                if (found == 10) {
                    msg = '<span id="msg">Congrats ! You Found All Pictures With </span>';
                    $("span.link").prepend(msg);
                    score = $("span.link");
                            $.ajax({
                                url: "users/" + id + "/updatescore", 
                                contentType: "application/json",
                                type: "POST",
                                data: JSON.stringify({ id: id, score: $("span.link").value}),
                                success: function (result) {
                                },
                                error: function (result) {                       
                             }
                            }); 
                }
            }
        }
    });
</script>

<style type="text/css">
    * {
        font-family: Arial, "Free Sans";
    }

    #boxcard {
        margin: 0 auto;
        width: 1000px;
        z-index: 1;
    }

    #boxcard div {
        float: left;
        width: 175px;
        height: 116px;
        background: #d9d9d9;
        margin: 5px;
        padding: 5px;
        border: 1px solid #999;
        cursor: pointer;
        -webkit-border-radius: .5em;
        -moz-border-radius: .5em;
        border-radius: .5em;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.5);
        -moz-box-shadow: 0 1px 2px rgba(0,0,0,.5);
        box-shadow: 0 1px 2px rgba(0,0,0,.5);
        z-index: 2;
    }

    #boxcard div img {
        border: none;
        z-index: 3;
    }

    .opacity {
        opacity: .6;
        filter: alpha(opacity=60);
    }

    #boxbutton {
        text-align: center;
        padding: 20px;
    }

    .link {
        font-size: 18px;
        color: #ffffff;
        text-decoration: none;
        background: #0066cc;
        padding: 5px 10px;
        -webkit-border-radius: .5em;
        -moz-border-radius: .5em;
        border-radius: .5em;
    }

    .link:hover {
        background: #999;
    }

    .opencard {
    position: relative;
    width: 175px;
    height: 116px;
    margin: 10px;
    float: left
    }

    .text {
        color: white;
        display: none;
        position: absolute;
        bottom: 0;
        left: 0;
        width: 30%;
        background: #999;
        background: rgba(0,0,0,0.3);
        text-align: center;
    }

    .opencard:hover .text {
        display: block;
    }

    .opencard:hover {
        opacity: 0.7;
    }

    #element_to_pop_up { 
        display:none;
    }
</style>


<div id="boxbutton">
    <span class="link">
        <span id="count">0</span>
        Click
    </span>
    &nbsp;
    <a href="javascript:location.reload()" class="link">Reset</a>
</div>

<form action="javascript:search();" method="post"> <br>  <input id="input" type="text" value="Type an annotated tag in here and click on the Search button!"/> <input type='submit' value='Search' /> </form>

<div id="boxcard">
    <% count = 0 %>    
    <% @entities.each do |entity| %>
        <div id="card<%= count %>"><img src="https://quiet-fortress-7864.herokuapp.com/entities/<%= entity.id %>/load_image">
            <span class="text">zoom</span>
        </div>
        <% count += 1 %>
    <%end%>

    <% count = 0 %> 
    <% @entities.each do |entity| %>
        <div id="card1<%= count %>"><img src="https://quiet-fortress-7864.herokuapp.com/entities/<%= entity.id %>/load_image">
            <span class="text">zoom</span>
        </div>
        <% count += 1 %>
    <%end%>
</div>


<!--
<div id="boxcard">
    <div id="card1"><img src="/01.jpg" style="" /><span class="text">zoom</span></div>
    <div id="card2"><img src="/02.jpg" style="" /><span class="text">zoom</span></div>
    <div id="card3"><img src="/03.jpg" style="" /><span class="text">zoom</span></div>
    <div id="card4"><img src="/04.jpg" style="" /><span class="text">zoom</span></div>
    <div id="card5"><img src="/05.jpg" style="" /><span class="text">zoom</span></div>
    <div id="card6"><img src="/06.jpg" style="" /><span class="text">zoom</span></div>
    <div id="card7"><img src="/07.jpg" style="" /><span class="text">zoom</span></div>
    <div id="card8"><img src="/08.jpg" style="" /><span class="text">zoom</span></div>
    <div id="card9"><img src="/09.jpg" style="" /><span class="text">zoom</span></div>
    <div id="card10"><img src="/10.jpg" style="" /><span class="text">zoom</span></div>
    <div id="card11"><img src="/01.jpg" style="" /><span class="text">zoom</span></div>
    <div id="card12"><img src="/02.jpg" style="" /><span class="text">zoom</span></div>
    <div id="card13"><img src="/03.jpg" style="" /><span class="text">zoom</span></div>
    <div id="card14"><img src="/04.jpg" style="" /><span class="text">zoom</span></div>
    <div id="card15"><img src="/05.jpg" style="" /><span class="text">zoom</span></div>
    <div id="card16"><img src="/06.jpg" style="" /><span class="text">zoom</span></div>
    <div id="card17"><img src="/07.jpg" style="" /><span class="text">zoom</span></div>
    <div id="card18"><img src="/08.jpg" style="" /><span class="text">zoom</span></div>
    <div id="card19"><img src="/09.jpg" style="" /><span class="text">zoom</span></div>
    <div id="card20"><img src="/10.jpg" style="" /><span class="text">zoom</span></div>        
</div>
-->

<!-- Element to pop up -->
<div id="element_to_pop_up"></div>

app/views/entities/index.html.erb
<h1>Listing entities</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Mine type</th>
      <th>Filename</th>
      <th>Tags</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @entities.each do |entity| %>
      <tr>
        <td><%= image_tag load_image_entity_path(entity.id) %></td>
        <td><%= entity.latitude %></td>
        <td><%= entity.longitude %></td>
        <td><%= entity.mine_type %></td>
        <td><%= entity.filename %></td>
        <td><%= entity.tags %></td>
        <td><%= link_to 'Show', entity %></td>
        <td><%= link_to 'Edit', edit_entity_path(entity) %></td>
        <td><%= link_to 'Destroy', entity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entity', new_entity_path %>

app/views/entities/new.html.erb
<h1>New entity</h1>

<%= render 'form' %>

<%= link_to 'Back', entities_path %>

app/views/entities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @entity.image %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @entity.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @entity.longitude %>
</p>

<p>
  <strong>Mine type:</strong>
  <%= @entity.mine_type %>
</p>

<p>
  <strong>Filename:</strong>
  <%= @entity.filename %>
</p>

<%= link_to 'Edit', edit_entity_path(@entity) %> |
<%= link_to 'Back', entities_path %>